### ISSUE TITLE
This repository does not have the license file.

### ISSUE THREAD

**Issue by Pythone** [dgl/cgiirc#18]
(https://sourceforge.net/projects/cgiirc/) the original repo has GPL v2 as the license, this repo also need to have gpl v2 as the license(But it does not mention it at all) can you add said license?

**Comment by dgl** [comment]
@janicez I can only assume you're trolling, the top of the main pieces of code have the licence and there's a COPYING file at https://github.com/dgl/cgiirc/blob/master/docs/COPYING
