### ISSUE TITLE
CGI::IRC incompatible with HTTP/2.0

### ISSUE THREAD

**Issue by a-v-s** [dgl/cgiirc#19]
I have been experiencing issues with an CGI::IRC installation lately. 
CGI::IRC does not seem to be loading correctly when the web server is configured for the HTTP/2.0 protocol. 
When the subdomain CGI::IRC is running on is restricted to HTTP/1.1, CGI::IRC works properly.
This behaviour is observed when running on Apache 2.4.58.

**Comment by dgl** [comment]
This is almost certainly an Apache issue, HTTP/2 itself has very good support for streaming (and even bidirectional streams). Apache has had various bugs over the years relating to CGI and/or NPH scripts; you may find renaming `nph-irc.cgi` to `main-irc.cgi` (and updating `cgiirc.config`) works around this, if not just disabling HTTP/2 is probably the best workaround like you've found.
