### ISSUE TITLE
How can i  get it run in openshift?

### ISSUE THREAD

**Issue by tvvocold** [dgl/cgiirc#8]
i had try 
$rhc app-create cgiirc perl-5.10
ssh in and $git clone https://github.com/dgl/cgiirc.git
edit the cgiirc.config and i change the .htaccess.

**Comment by tvvocold** [comment]
i got it run but i got 500 error when i click login. why?
https://perl-googleshell.rhcloud.com

**Comment by tvvocold** [comment]
It looks like https://github.com/dgl/cgiirc/tree/master/interfaces is some how missing mozilla.pm  
So i $wget http://cgiirc.org/releases/cgiirc-0.5.11.tar.gz

**Comment by dgl** [comment]
Yes, the git version needs building, you can add running
make-js-interfaces.pl to your setup or just use the tarball.

**Comment by tvvocold** [comment]
i use the tarball but no matter i edit the cgiirc.config file the server always got disconnet.
here is the site: http://irc.fdzh.org
